<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Capturing Screenshot]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Jun_30_20_59_59_IST_2020.jpg><img src=Tue_Jun_30_20_59_59_IST_2020.jpg height=100 width=100></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Page Object Model" duration-ms="14063" started-at="2020-06-30T20:59:55 IST" finished-at="2020-06-30T21:00:10 IST">
    <groups>
    </groups>
    <test name="Zoho App Test" duration-ms="14063" started-at="2020-06-30T20:59:55 IST" finished-at="2020-06-30T21:00:10 IST">
      <class name="com.practice.testcases.CreateAccountTest">
        <test-method status="PASS" signature="createAccountTest(java.util.Hashtable)[pri:0, instance:com.practice.testcases.CreateAccountTest@6bd51ed8]" name="createAccountTest" duration-ms="9120" started-at="2020-06-30T21:00:00 IST" data-provider="dp" finished-at="2020-06-30T21:00:09 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{accountName=Sheldon Cooper}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
      </class> <!-- com.practice.testcases.CreateAccountTest -->
      <class name="com.practice.testcases.LoginTest">
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.practice.testcases.LoginTest@271f18d3]" name="loginTest" duration-ms="2686" started-at="2020-06-30T20:59:56 IST" data-provider="dp" finished-at="2020-06-30T20:59:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{recRunMode=Y, password=Tekion@123, userName=24x7work08@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Test Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Test Failed
at org.testng.Assert.fail(Assert.java:97)
at com.practice.testcases.LoginTest.loginTest(LoginTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing Screenshot]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Jun_30_20_59_59_IST_2020.jpg><img src=Tue_Jun_30_20_59_59_IST_2020.jpg height=100 width=100></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.practice.testcases.LoginTest@271f18d3]" name="tearDown" is-config="true" duration-ms="745" started-at="2020-06-30T21:00:10 IST" finished-at="2020-06-30T21:00:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.practice.testcases.LoginTest -->
    </test> <!-- Zoho App Test -->
  </suite> <!-- Page Object Model -->
</testng-results>
